---
title: "Authorship"
---

```{r setup, include = FALSE}
library(tidyverse)
library(knitr)
library(plotly)
library(scales)
library(ggthemes)
library(lubridate)
library(knitr)
library(stringr)

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

theme_set(theme_minimal())

catalogue <- read.csv("Data/inspire_catalogue.csv") %>%
  rename(Issue = `ï..Issue`) %>%
  transform(Issue = as.double(Issue)) %>%
  transform(NumPages = as.double(NumPages)) %>%
  transform(ItemType = as.character(ItemType)) %>%
  transform(ItemType = ifelse(ItemType %in% c("Poetry", "Photography"), "Art and Poetry", ItemType)) %>%
  transform(ItemType = as.factor(ItemType)) %>%
  transform(ItemType = factor(ItemType, levels = ItemType)) %>%
  transform(AuthorName = as.character(AuthorName)) %>%
  transform(AuthorName = ifelse(AuthorName == "Usama Bin Laden", "Usama bin Laden", AuthorName)) %>%
  transform(AuthorName = ifelse(AuthorName == "AQ Chef", "'AQ Chef'", AuthorName)) %>%
  transform(AuthorName = ifelse(AuthorName == "Terr0r1st", "'Terr0r1st'", AuthorName))
```
```{r original_content}
original <- catalogue %>%
  filter(!is.na(OriginalContent)) %>%
  group_by(Issue, OriginalContent) %>%
  summarize(orig_freq = n())

original_n <- catalogue %>%
  filter(!is.na(OriginalContent)) %>%
  group_by(Issue) %>%
  summarize(tot_num = n())

original <- left_join(original, original_n, by = "Issue") %>%
  mutate(orig_freq_weight = orig_freq/tot_num) %>%
  arrange(OriginalContent) %>%
  transform(OriginalContent = ifelse(OriginalContent == 0, "No", "Yes")) %>%
  transform(OriginalContent = as.factor(OriginalContent)) %>%
  transform(OriginalContent = factor(OriginalContent, levels = OriginalContent))

orig <- ggplot(original, aes(Issue, orig_freq_weight)) + 
  geom_bar(aes(fill = OriginalContent), stat = "identity") + 
  labs(title = "Percentage of articles written for article, by issue",
       x = "Issue", y = "Percentage of articles",
       fill = "Original Content?") + 
  scale_fill_manual(values = c("#4B0082", "#FFD700")) + 
  scale_x_continuous(breaks = seq(1, 16, 1)) + 
  scale_y_continuous(labels = percent_format()) + 
  theme_classic() + 
  theme(axis.ticks.x = element_blank())

porig <- plotly_build(orig)

porig
```

to fix: clean up hover labels

```{r authors_num}
authors_all_issues <- catalogue %>%
  filter(!is.na(AuthorName) & !AuthorName %in% c("Various", 
                                                "Al-Qaeda in the Arabian Peninsula",
                                                "Al-Malahem",
                                                "External Operations Team",
                                                "Reconaissance Team",
                                                "Experts")) %>%
  count(AuthorName) %>%
  arrange(n) %>%
  filter(n >= 3) %>%
  transform(AuthorName = as.factor(AuthorName)) %>%
  transform(AuthorName = factor(AuthorName, levels = AuthorName))
```

`r nrow(authors_all_issues)` (presumably) individual authors

Hover over the red points to learn more about the authors

```{r authors_chart}
author_info <- read.csv("Data/author_info.csv", colClasses = c("factor", "character"))

authors <- ggplot(authors_all_issues, aes(n, AuthorName)) + 
  geom_point(color = "#FF6347", size = 2) + 
  geom_segment(aes(x = 0, y = AuthorName, xend = n-0.05, yend = AuthorName),
               color = "#999999") +
  scale_x_continuous(breaks = seq(3, 11, 2)) + 
  labs(title = "Inspire Magazine: most featured authors",
       x = "Number of times featured",
       y = "") + 
  theme_minimal() + 
  theme(plot.title = element_text(size = 14),
        axis.title = element_text(size = 12),
        panel.grid.minor = element_blank())

pauthors <- plotly_build(authors)

pauthors$x$data[[1]]$text <- author_info$X
pauthors$x$data[[2]]$text <- ""
pauthors
```

to fix: make hover text neater - make text bubbles more uniform in width