---
title: "Content"
---

```{r setup, include = FALSE}
library(tidyverse)
library(knitr)
library(plotly)
library(scales)
library(ggthemes)
library(lubridate)
library(knitr)
library(stringr)

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

theme_set(theme_minimal())

catalogue <- read.csv("Data/inspire_catalogue.csv") %>%
  rename(Issue = `ï..Issue`) %>%
  transform(Issue = as.double(Issue)) %>%
  transform(NumPages = as.double(NumPages)) %>%
  transform(ItemType = as.character(ItemType)) %>%
  transform(ItemType = ifelse(ItemType %in% c("Poetry", "Photography"), "Art and Poetry", ItemType)) %>%
  transform(ItemType = as.factor(ItemType)) %>%
  transform(ItemType = factor(ItemType, levels = ItemType)) %>%
  transform(AuthorName = as.character(AuthorName)) %>%
  transform(AuthorName = ifelse(AuthorName == "Usama Bin Laden", "Usama bin Laden", AuthorName)) %>%
  transform(AuthorName = ifelse(AuthorName == "AQ Chef", "'AQ Chef'", AuthorName)) %>%
  transform(AuthorName = ifelse(AuthorName == "Terr0r1st", "'Terr0r1st'", AuthorName))
```

Description of categories and methods

```{r content_aggregate}
cat_type <- catalogue %>%
  group_by(ItemType) %>%
  summarize(SumPages = sum(NumPages)) %>%
  arrange(desc(SumPages)) %>%
  mutate(TotPages = sum(SumPages)) %>%
  mutate(page_freq_weight = SumPages/TotPages) %>%
  transform(ItemType = as.factor(ItemType)) %>%
  transform(ItemType = factor(ItemType, levels = ItemType))

cat_all <- ggplot(cat_type, aes(ItemType, page_freq_weight)) + 
  geom_point(color = "#4f86f7", size = 2) + 
  geom_segment(aes(x = ItemType, y = 0, xend = ItemType, yend = page_freq_weight - 0.005),
               color = "#C0C0C0") + 
  labs(title = "Distribution of categories",
       x = "Category", y = "Percentage of pages") + 
  scale_y_continuous(limits = c(0, 0.3), breaks = seq(0, 0.3, .1), labels=percent) + 
  #scale_color_manual(values = c("#AA4499", "#882255", "#AA4466", "#CC6677", "#661100", "#DDCC77", "#999933", #"#117733", "#44AA99", "#88CCEE", "#6699CC", "#332288")) + 
  theme(panel.grid.major.x = element_blank(),
        axis.text.x = element_text(angle = -60, hjust = 0.3),
        axis.title.x = element_blank())

pcat_all <- plotly_build(cat_all)

pcat_all$x$layout$margin$b <- 120
pcat_all$x$layout$margin$l <- 60
pcat_all$x$layout$showlegend <- FALSE

pcat_all
```

to fix: add some padding to bottom so labels show up, clean up hover text

by issue

```{r content_by_issue}
cat_issue_type <- catalogue %>%
  group_by(Issue, ItemType) %>%
  summarize(SumPages = sum(NumPages)) %>%
  ungroup()

find_missing_type <- function(issue) {
  data = dplyr::filter(cat_issue_type, Issue == issue)
  TypeList = data$ItemType
  missing = cat_type$ItemType[!cat_type$ItemType %in% TypeList]
  
  return(missing)
}

make_row <- function(issue, missing_type) {
  row = t(as_tibble(c(issue, missing_type, 0)))
  colnames(row) <- c("Issue", "ItemType", "SumPages")
  row = as.data.frame(row)
  rownames(row) <- NULL
  return(row)
}

make_rows <- function(issue) {
  missing = find_missing_type(issue)
  missing_rows = make_row(issue, as.character(missing[1]))
  if (length(missing) > 1) {
    for (x in tail(missing, -1)) {
    missing_rows = rbind(missing_rows, make_row(issue, as.character(x)))
    }
  }
  else {
    missing_rows = missing_rows
  }
  
  return(missing_rows)
}

missing_rows <- make_rows(1)
for (x in seq(2,16)) {
  missing_rows <- rbind(missing_rows, make_rows(x))
}

missing_rows <- missing_rows %>%
  transform(Issue = as.numeric(Issue)) %>%
  transform(SumPages = as.numeric(SumPages) - 1)

cat_issue_type <- rbind(cat_issue_type, missing_rows) %>%
  arrange(Issue) %>%
  na.omit()

TotPages <- catalogue %>%
  group_by(Issue) %>%
  summarize(TotalPages = sum(NumPages))

cat_issue_type <- left_join(cat_issue_type, TotPages) %>%
  mutate(SharePages = SumPages/TotalPages)

rep1 <- cat_issue_type %>%
  transform(Issue = Issue + 0.5)

rep2 <- cat_issue_type %>%
  transform(Issue = Issue + 0.9999)

cat_join <- bind_rows(cat_issue_type, rbind(rep1, rep2)) %>%
  transform(ItemType = as.factor(ItemType)) %>%
  transform(ItemType = factor(ItemType, levels = rev(cat_type$ItemType)))

#ggplot(cat_issue_type, aes(x=Issue, y=SumPages, fill=ItemType)) + 
#  geom_area() + 
#  scale_x_continuous(breaks = seq(1, 16, 1))

#ggplot(cat_issue_type, aes(x=Issue, y=SharePages, fill=ItemType)) + 
#  geom_area(color = "black") + 
#  scale_x_continuous(breaks = seq(1, 16, 1))

cat_issue <- ggplot(cat_join, aes(x=Issue, y=SharePages, fill=ItemType)) + 
  geom_area(color = "white") + 
  scale_x_continuous(breaks = seq(1.5, 16.5, 1), labels = seq(1, 16, 1)) + 
  scale_y_continuous(labels = percent_format()) + 
  labs(title = "Share of pages per category, by issue",
       x = "Issue", y = "Percentage of total",
       fill = "Category") + 
  scale_fill_ptol() + 
  theme_classic()

pcat_issue <- plotly_build(cat_issue)

pcat_issue
```


