---
title: "About This Project"
---

## Purpose

This website serves as an interactive visual exploration of various aspects of a particularly salient terrorist publication, *Inspire* magazine produced by al-Qaeda's affiliate al-Qaeda in the Arabian Peninsula (AQAP). By visualizing data drawn from all current issues of the magazines, I hope to demystify some aspects of militant jihadist propaganda and dispel some misunderstandings that may arise due to unfamiliarity or media hype.

The specific questions that I answer in this visualization are:

* What is included in these issues? What categories are covered and how does the coverage change across issue? 
* Who is involved? Who are the main contributors, and what is their role in al-Qaeda's network?
* How much of the content is original? What proportion of articles are written specifically for *Inspire* or drawn from other sources?

The answers to these questions hold practical implications for counter-terrorism, but the visualization also provides an accessible introduction to terrorist messaging for members of the public who are interested in the phenomenon.

## Design description

Throughout the visualization, I employ a theme of "illuminating" - that is, shedding light on the issue at hand. That applies figuratively in the sense of providing information and producing insight and also somewhat literally in the color scheme. Instead of accomodating the inherent darkness of the material, I contrast it with a bright white background, pleasant jewel tones, and fun shapes (e.g. lollipop charts in place of the traditional bar charts). Symbolically, this represents a refusal to be terrorized, or to cloud judgment with dark feelings of anger and feel. 

In addition, I use interactive elements to engage the reader and provide more information than would be available using static images. 